spring.application.name=demo
server.port=8080

server.error.include-stacktrace=never
server.error.include-message=never
server.error.include-binding-errors=never

logging.file.name=logs/app.log

spring.datasource.url=jdbc:mysql://localhost:3306/employeedb
spring.datasource.username=${DB_USERNAME:employee_app}
spring.datasource.password=${DB_PASSWORD:employee_app}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false